import 'dart:ui';
import 'package:flutter/material.dart';

// ==================== 组织类型 → 颜色映射 ====================
enum TissueType { bone, muscle, joint, organ }

const tissueColors = {
  TissueType.bone: Color(0xFF42A5F5),
  TissueType.muscle: Color(0xFFEF5350),
  TissueType.joint: Color(0xFFFFC107),
  TissueType.organ: Color(0xFF66BB6A),
};

const tissueDarkColors = {
  TissueType.bone: Color(0xFF1565C0),
  TissueType.muscle: Color(0xFFB71C1C),
  TissueType.joint: Color(0xFFF57F17),
  TissueType.organ: Color(0xFF2E7D32),
};

const tissueLabels = {
  TissueType.bone: '骨骼',
  TissueType.muscle: '肌肉',
  TissueType.joint: '关节',
  TissueType.organ: '区域',
};

// ==================== 色块形状 ====================
enum BlockShape { rect, roundedRect, circle, stadium }

// ==================== 色块区域 ====================
class BlockRegion {
  final String id;
  final String label;
  final TissueType tissue;
  final BlockShape shape;
  final double x, y, w, h;
  final double radius;
  final List<BlockRegion> children;

  const BlockRegion({
    required this.id,
    required this.label,
    required this.tissue,
    this.shape = BlockShape.roundedRect,
    required this.x,
    required this.y,
    required this.w,
    required this.h,
    this.radius = 8,
    this.children = const [],
  });

  bool get hasChildren => children.isNotEmpty;
  Rect get rect => Rect.fromLTWH(x, y, w, h);

  bool hitTest(Offset point) {
    switch (shape) {
      case BlockShape.circle:
        final center = Offset(x + w / 2, y + h / 2);
        return (point - center).distance <= w / 2;
      default:
        return rect.contains(point);
    }
  }
}

// ==================== 全身色块定义（标准画布 400×800）====================
final fullBodyRegions = [
  // ---- 头部 ----
  BlockRegion(
    id: 'head',
    label: '头部',
    tissue: TissueType.organ,
    shape: BlockShape.roundedRect,
    x: 160,
    y: 10,
    w: 80,
    h: 90,
    radius: 40,
    children: [
      BlockRegion(
        id: 'skull',
        label: '颅骨',
        tissue: TissueType.bone,
        x: 100,
        y: 20,
        w: 200,
        h: 120,
        radius: 60,
      ),
      BlockRegion(
        id: 'face_muscle',
        label: '面部肌群',
        tissue: TissueType.muscle,
        x: 130,
        y: 160,
        w: 140,
        h: 80,
        radius: 20,
      ),
      BlockRegion(
        id: 'jaw_joint',
        label: '颞下颌关节(左)',
        tissue: TissueType.joint,
        shape: BlockShape.circle,
        x: 90,
        y: 180,
        w: 40,
        h: 40,
      ),
      BlockRegion(
        id: 'jaw_joint_r',
        label: '颞下颌关节(右)',
        tissue: TissueType.joint,
        shape: BlockShape.circle,
        x: 270,
        y: 180,
        w: 40,
        h: 40,
      ),
    ],
  ),
  // ---- 颈部 ----
  BlockRegion(
    id: 'neck',
    label: '颈部',
    tissue: TissueType.muscle,
    x: 175,
    y: 105,
    w: 50,
    h: 30,
    radius: 10,
    children: [
      BlockRegion(
        id: 'cervical_spine',
        label: '颈椎',
        tissue: TissueType.bone,
        x: 170,
        y: 20,
        w: 60,
        h: 300,
        radius: 10,
      ),
      BlockRegion(
        id: 'sternocleidomastoid',
        label: '胸锁乳突肌',
        tissue: TissueType.muscle,
        x: 80,
        y: 40,
        w: 100,
        h: 200,
        radius: 14,
      ),
      BlockRegion(
        id: 'throat',
        label: '喉咙',
        tissue: TissueType.organ,
        x: 150,
        y: 200,
        w: 100,
        h: 100,
        radius: 16,
      ),
      BlockRegion(
        id: 'thyroid',
        label: '甲状腺',
        tissue: TissueType.organ,
        shape: BlockShape.circle,
        x: 160,
        y: 380,
        w: 80,
        h: 80,
      ),
    ],
  ),
  // ---- 肩关节 ----
  BlockRegion(
    id: 'shoulder_l',
    label: '左肩',
    tissue: TissueType.joint,
    shape: BlockShape.circle,
    x: 110,
    y: 130,
    w: 40,
    h: 40,
  ),
  BlockRegion(
    id: 'shoulder_r',
    label: '右肩',
    tissue: TissueType.joint,
    shape: BlockShape.circle,
    x: 250,
    y: 130,
    w: 40,
    h: 40,
  ),
  // ---- 躯干 ----
  BlockRegion(
    id: 'torso',
    label: '躯干',
    tissue: TissueType.organ,
    x: 145,
    y: 140,
    w: 110,
    h: 160,
    radius: 12,
    children: [
      BlockRegion(
        id: 'chest_muscle',
        label: '胸肌',
        tissue: TissueType.muscle,
        x: 110,
        y: 30,
        w: 180,
        h: 100,
        radius: 16,
      ),
      BlockRegion(
        id: 'spine',
        label: '脊柱',
        tissue: TissueType.bone,
        x: 185,
        y: 20,
        w: 30,
        h: 350,
        radius: 8,
      ),
      BlockRegion(
        id: 'ribs',
        label: '肋骨',
        tissue: TissueType.bone,
        x: 120,
        y: 60,
        w: 160,
        h: 120,
        radius: 12,
      ),
      BlockRegion(
        id: 'abs',
        label: '腹肌',
        tissue: TissueType.muscle,
        x: 140,
        y: 200,
        w: 120,
        h: 120,
        radius: 10,
      ),
    ],
  ),
  // ---- 上臂 ----
  BlockRegion(
    id: 'upper_arm_l',
    label: '左上臂',
    tissue: TissueType.muscle,
    x: 95,
    y: 170,
    w: 35,
    h: 90,
    radius: 12,
    children: [
      BlockRegion(
        id: 'deltoid_l',
        label: '三角肌',
        tissue: TissueType.muscle,
        x: 80,
        y: 20,
        w: 140,
        h: 100,
        radius: 16,
      ),
      BlockRegion(
        id: 'biceps_l',
        label: '肱二头肌',
        tissue: TissueType.muscle,
        x: 80,
        y: 140,
        w: 120,
        h: 120,
        radius: 14,
      ),
      BlockRegion(
        id: 'triceps_l',
        label: '肱三头肌',
        tissue: TissueType.muscle,
        x: 200,
        y: 140,
        w: 120,
        h: 120,
        radius: 14,
      ),
      BlockRegion(
        id: 'humerus_l',
        label: '肱骨',
        tissue: TissueType.bone,
        x: 150,
        y: 20,
        w: 20,
        h: 320,
        radius: 6,
      ),
    ],
  ),
  BlockRegion(
    id: 'upper_arm_r',
    label: '右上臂',
    tissue: TissueType.muscle,
    x: 270,
    y: 170,
    w: 35,
    h: 90,
    radius: 12,
    children: [
      BlockRegion(
        id: 'deltoid_r',
        label: '三角肌',
        tissue: TissueType.muscle,
        x: 80,
        y: 20,
        w: 140,
        h: 100,
        radius: 16,
      ),
      BlockRegion(
        id: 'biceps_r',
        label: '肱二头肌',
        tissue: TissueType.muscle,
        x: 80,
        y: 140,
        w: 120,
        h: 120,
        radius: 14,
      ),
      BlockRegion(
        id: 'triceps_r',
        label: '肱三头肌',
        tissue: TissueType.muscle,
        x: 200,
        y: 140,
        w: 120,
        h: 120,
        radius: 14,
      ),
      BlockRegion(
        id: 'humerus_r',
        label: '肱骨',
        tissue: TissueType.bone,
        x: 150,
        y: 20,
        w: 20,
        h: 320,
        radius: 6,
      ),
    ],
  ),
  // ---- 肘关节 ----
  BlockRegion(
    id: 'elbow_l',
    label: '左肘',
    tissue: TissueType.joint,
    shape: BlockShape.circle,
    x: 85,
    y: 260,
    w: 30,
    h: 30,
  ),
  BlockRegion(
    id: 'elbow_r',
    label: '右肘',
    tissue: TissueType.joint,
    shape: BlockShape.circle,
    x: 285,
    y: 260,
    w: 30,
    h: 30,
  ),
  // ---- 前臂 ----
  BlockRegion(
    id: 'forearm_l',
    label: '左前臂',
    tissue: TissueType.muscle,
    x: 80,
    y: 290,
    w: 30,
    h: 80,
    radius: 10,
    children: [
      BlockRegion(
        id: 'radius_l',
        label: '桡骨',
        tissue: TissueType.bone,
        x: 120,
        y: 20,
        w: 20,
        h: 280,
        radius: 6,
      ),
      BlockRegion(
        id: 'ulna_l',
        label: '尺骨',
        tissue: TissueType.bone,
        x: 200,
        y: 20,
        w: 20,
        h: 280,
        radius: 6,
      ),
      BlockRegion(
        id: 'forearm_flexor_l',
        label: '前臂屈肌',
        tissue: TissueType.muscle,
        x: 100,
        y: 100,
        w: 140,
        h: 140,
        radius: 14,
      ),
      BlockRegion(
        id: 'forearm_extensor_l',
        label: '前臂伸肌',
        tissue: TissueType.muscle,
        x: 100,
        y: 260,
        w: 140,
        h: 120,
        radius: 14,
      ),
    ],
  ),
  BlockRegion(
    id: 'forearm_r',
    label: '右前臂',
    tissue: TissueType.muscle,
    x: 290,
    y: 290,
    w: 30,
    h: 80,
    radius: 10,
    children: [
      BlockRegion(
        id: 'radius_r',
        label: '桡骨',
        tissue: TissueType.bone,
        x: 120,
        y: 20,
        w: 20,
        h: 280,
        radius: 6,
      ),
      BlockRegion(
        id: 'ulna_r',
        label: '尺骨',
        tissue: TissueType.bone,
        x: 200,
        y: 20,
        w: 20,
        h: 280,
        radius: 6,
      ),
      BlockRegion(
        id: 'forearm_flexor_r',
        label: '前臂屈肌',
        tissue: TissueType.muscle,
        x: 100,
        y: 100,
        w: 140,
        h: 140,
        radius: 14,
      ),
      BlockRegion(
        id: 'forearm_extensor_r',
        label: '前臂伸肌',
        tissue: TissueType.muscle,
        x: 100,
        y: 260,
        w: 140,
        h: 120,
        radius: 14,
      ),
    ],
  ),
  // ---- 手 ----
  BlockRegion(
    id: 'hand_l',
    label: '左手',
    tissue: TissueType.bone,
    x: 72,
    y: 375,
    w: 35,
    h: 40,
    radius: 10,
    children: [
      BlockRegion(
        id: 'wrist_l',
        label: '腕关节',
        tissue: TissueType.joint,
        shape: BlockShape.circle,
        x: 140,
        y: 30,
        w: 120,
        h: 80,
      ),
      BlockRegion(
        id: 'palm_l',
        label: '掌骨',
        tissue: TissueType.bone,
        x: 110,
        y: 120,
        w: 180,
        h: 120,
        radius: 14,
      ),
      BlockRegion(
        id: 'fingers_l',
        label: '手指',
        tissue: TissueType.bone,
        x: 80,
        y: 260,
        w: 240,
        h: 100,
        radius: 12,
      ),
    ],
  ),
  BlockRegion(
    id: 'hand_r',
    label: '右手',
    tissue: TissueType.bone,
    x: 293,
    y: 375,
    w: 35,
    h: 40,
    radius: 10,
    children: [
      BlockRegion(
        id: 'wrist_r',
        label: '腕关节',
        tissue: TissueType.joint,
        shape: BlockShape.circle,
        x: 140,
        y: 30,
        w: 120,
        h: 80,
      ),
      BlockRegion(
        id: 'palm_r',
        label: '掌骨',
        tissue: TissueType.bone,
        x: 110,
        y: 120,
        w: 180,
        h: 120,
        radius: 14,
      ),
      BlockRegion(
        id: 'fingers_r',
        label: '手指',
        tissue: TissueType.bone,
        x: 80,
        y: 260,
        w: 240,
        h: 100,
        radius: 12,
      ),
    ],
  ),
  // ---- 髋关节 ----
  BlockRegion(
    id: 'hip_l',
    label: '左髋',
    tissue: TissueType.joint,
    shape: BlockShape.circle,
    x: 150,
    y: 305,
    w: 35,
    h: 35,
  ),
  BlockRegion(
    id: 'hip_r',
    label: '右髋',
    tissue: TissueType.joint,
    shape: BlockShape.circle,
    x: 215,
    y: 305,
    w: 35,
    h: 35,
  ),
  // ---- 大腿 ----
  BlockRegion(
    id: 'thigh_l',
    label: '左大腿',
    tissue: TissueType.muscle,
    x: 148,
    y: 340,
    w: 50,
    h: 130,
    radius: 14,
    children: [
      BlockRegion(
        id: 'quad_l',
        label: '左股四头肌',
        tissue: TissueType.muscle,
        x: 100,
        y: 30,
        w: 120,
        h: 150,
        radius: 16,
      ),
      BlockRegion(
        id: 'hamstring_l',
        label: '左腘绳肌',
        tissue: TissueType.muscle,
        x: 100,
        y: 200,
        w: 120,
        h: 140,
        radius: 16,
      ),
      BlockRegion(
        id: 'femur_l',
        label: '左股骨',
        tissue: TissueType.bone,
        x: 150,
        y: 20,
        w: 24,
        h: 320,
        radius: 8,
      ),
    ],
  ),
  BlockRegion(
    id: 'thigh_r',
    label: '右大腿',
    tissue: TissueType.muscle,
    x: 202,
    y: 340,
    w: 50,
    h: 130,
    radius: 14,
    children: [
      BlockRegion(
        id: 'quad_r',
        label: '右股四头肌',
        tissue: TissueType.muscle,
        x: 100,
        y: 30,
        w: 120,
        h: 150,
        radius: 16,
      ),
      BlockRegion(
        id: 'hamstring_r',
        label: '右腘绳肌',
        tissue: TissueType.muscle,
        x: 100,
        y: 200,
        w: 120,
        h: 140,
        radius: 16,
      ),
      BlockRegion(
        id: 'femur_r',
        label: '右股骨',
        tissue: TissueType.bone,
        x: 150,
        y: 20,
        w: 24,
        h: 320,
        radius: 8,
      ),
    ],
  ),
  // ---- 膝关节 ----
  BlockRegion(
    id: 'knee_l',
    label: '左膝',
    tissue: TissueType.joint,
    shape: BlockShape.circle,
    x: 155,
    y: 475,
    w: 35,
    h: 35,
  ),
  BlockRegion(
    id: 'knee_r',
    label: '右膝',
    tissue: TissueType.joint,
    shape: BlockShape.circle,
    x: 210,
    y: 475,
    w: 35,
    h: 35,
  ),
  // ---- 小腿 ----
  BlockRegion(
    id: 'calf_l',
    label: '左小腿',
    tissue: TissueType.muscle,
    x: 150,
    y: 515,
    w: 42,
    h: 130,
    radius: 12,
    children: [
      BlockRegion(
        id: 'tibia_l',
        label: '胫骨',
        tissue: TissueType.bone,
        x: 140,
        y: 20,
        w: 20,
        h: 300,
        radius: 6,
      ),
      BlockRegion(
        id: 'fibula_l',
        label: '腓骨',
        tissue: TissueType.bone,
        x: 220,
        y: 20,
        w: 16,
        h: 280,
        radius: 5,
      ),
      BlockRegion(
        id: 'gastrocnemius_l',
        label: '腓肠肌',
        tissue: TissueType.muscle,
        x: 100,
        y: 80,
        w: 160,
        h: 180,
        radius: 16,
      ),
      BlockRegion(
        id: 'soleus_l',
        label: '比目鱼肌',
        tissue: TissueType.muscle,
        x: 110,
        y: 260,
        w: 140,
        h: 100,
        radius: 14,
      ),
    ],
  ),
  BlockRegion(
    id: 'calf_r',
    label: '右小腿',
    tissue: TissueType.muscle,
    x: 208,
    y: 515,
    w: 42,
    h: 130,
    radius: 12,
    children: [
      BlockRegion(
        id: 'tibia_r',
        label: '胫骨',
        tissue: TissueType.bone,
        x: 140,
        y: 20,
        w: 20,
        h: 300,
        radius: 6,
      ),
      BlockRegion(
        id: 'fibula_r',
        label: '腓骨',
        tissue: TissueType.bone,
        x: 220,
        y: 20,
        w: 16,
        h: 280,
        radius: 5,
      ),
      BlockRegion(
        id: 'gastrocnemius_r',
        label: '腓肠肌',
        tissue: TissueType.muscle,
        x: 100,
        y: 80,
        w: 160,
        h: 180,
        radius: 16,
      ),
      BlockRegion(
        id: 'soleus_r',
        label: '比目鱼肌',
        tissue: TissueType.muscle,
        x: 110,
        y: 260,
        w: 140,
        h: 100,
        radius: 14,
      ),
    ],
  ),
  // ---- 踝关节 ----
  BlockRegion(
    id: 'ankle_l',
    label: '左踝',
    tissue: TissueType.joint,
    shape: BlockShape.circle,
    x: 155,
    y: 650,
    w: 28,
    h: 28,
  ),
  BlockRegion(
    id: 'ankle_r',
    label: '右踝',
    tissue: TissueType.joint,
    shape: BlockShape.circle,
    x: 215,
    y: 650,
    w: 28,
    h: 28,
  ),
  // ---- 足 ----
  BlockRegion(
    id: 'foot_l',
    label: '左脚',
    tissue: TissueType.bone,
    x: 140,
    y: 680,
    w: 50,
    h: 30,
    radius: 10,
    children: [
      BlockRegion(
        id: 'calcaneus_l',
        label: '跟骨',
        tissue: TissueType.bone,
        x: 160,
        y: 240,
        w: 80,
        h: 80,
        radius: 14,
      ),
      BlockRegion(
        id: 'metatarsal_l',
        label: '跖骨',
        tissue: TissueType.bone,
        x: 80,
        y: 60,
        w: 240,
        h: 100,
        radius: 12,
      ),
      BlockRegion(
        id: 'arch_l',
        label: '足弓',
        tissue: TissueType.joint,
        x: 100,
        y: 140,
        w: 200,
        h: 80,
        radius: 14,
      ),
    ],
  ),
  BlockRegion(
    id: 'foot_r',
    label: '右脚',
    tissue: TissueType.bone,
    x: 210,
    y: 680,
    w: 50,
    h: 30,
    radius: 10,
    children: [
      BlockRegion(
        id: 'calcaneus_r',
        label: '跟骨',
        tissue: TissueType.bone,
        x: 160,
        y: 240,
        w: 80,
        h: 80,
        radius: 14,
      ),
      BlockRegion(
        id: 'metatarsal_r',
        label: '跖骨',
        tissue: TissueType.bone,
        x: 80,
        y: 60,
        w: 240,
        h: 100,
        radius: 12,
      ),
      BlockRegion(
        id: 'arch_r',
        label: '足弓',
        tissue: TissueType.joint,
        x: 100,
        y: 140,
        w: 200,
        h: 80,
        radius: 14,
      ),
    ],
  ),
];
